services:
  spark-master:
    image: hanvocado/custom-spark:3.2
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_DRIVER_MEMORY=4g
      - SPARK_EXECUTOR_MEMORY=4g
    env_file:
      - ./spark/.env
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ./scripts:/opt/work/spark-scripts
      - ./spark/conf/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf

  spark-worker-1:
    image: hanvocado/custom-spark:3.2
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
    env_file:
      - ./spark/.env
    depends_on:
      - spark-master
    volumes:
      - ./spark/conf/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf

  spark-worker-2:
    image: hanvocado/custom-spark:3.2
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
    env_file:
      - ./spark/.env
    depends_on:
      - spark-master
    volumes:
      - ./spark/conf/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

  postgres-metastore:
    image: postgres:latest
    container_name: postgres-metastore
    environment:
      POSTGRES_DB: metastore
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hive"]
      interval: 10s
      timeout: 5s
      retries: 5

  hive-metastore:
    image: apache/hive:4.0.0
    container_name: hive-metastore
    depends_on:
      postgres-metastore:
        condition: service_healthy
    environment:
      - SERVICE_NAME=metastore
      - HIVE_METASTORE_DB_TYPE=postgres
      - HIVE_METASTORE_DB_HOST=postgres-metastore
      - HIVE_METASTORE_DB_NAME=metastore
      - HIVE_METASTORE_DB_USER=hive
      - HIVE_METASTORE_DB_PASS=hive
    env_file:
      - ./hive/.env
    volumes:
    - ./hive/jars/aws-java-sdk-bundle-1.12.150.jar:/opt/hive/lib/aws-java-sdk-bundle-1.12.150.jar
    - ./hive/jars/hadoop-aws-3.3.1.jar:/opt/hive/lib/hadoop-aws-3.3.1.jar
    - ./hive/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
    ports:
      - "9083:9083"
    command: >
      bash -c "
        /opt/hive/bin/schematool -initSchema -dbType postgres --verbose &&
        hive --service metastore
      "

  dremio:
    platform: linux/x86_64
    image: dremio/dremio-oss:latest
    ports:
      - 9047:9047 # Web UI
      - 31010:31010
      - 32010:32010
    container_name: dremio

volumes:
  minio-data:
