services:
  spark-master:
    image: custom-spark:3.3
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./spark/conf/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
    env_file:
      - .env
    ports:
      - "7077:7077"  # Spark Master
      - "8080:8080"  # Spark UI
    networks:
      - lakehouse

  spark-worker-1:
    image: custom-spark:3.3
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - ./spark/conf/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
    depends_on:
      - spark-master
    env_file:
      - .env
    networks:
      - lakehouse

  spark-worker-2:
    image: custom-spark:3.3
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - ./spark/conf/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
    env_file:
      - .env
    depends_on:
      - spark-master
    networks:
      - lakehouse
    
  spark-driver:
    image: custom-spark:3.3
    container_name: spark-driver
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=client
    env_file:
      - .env
    entrypoint: ["/bin/bash", "-c", "tail -f /dev/null"]
    volumes:
      - ./scripts:/app/spark-scripts
      - ./spark/conf/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
    networks:
      - lakehouse

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    networks:
      - lakehouse

  nessie:
    image: projectnessie/nessie:latest
    container_name: nessie
    ports:
      - "19120:19120"
    networks:
      - lakehouse

volumes:
  minio-data:

networks:
  lakehouse:
    driver: bridge